architectury {
    common rootProject.enabled_platforms.split(',')
}

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    implementation 'com.alibaba.fastjson2:fastjson2:2.0.50'
    implementation "org.xerial.snappy:snappy-java:1.1.10.8"
}
